image: node:16.17.1

definitions:
  steps:
    - step: &deploy
        name: Deploy to S3
        deployment: Staging
        script:
        - echo 'deployment on staging'
        - pwd
        - ls -l
        - npm install
        - npm run build
        - pipe: atlassian/aws-s3-deploy:0.3.8
          variables:
             AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
             AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
             AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
             S3_BUCKET: $S3_BUCKET
             LOCAL_PATH: 'build'
             DELETE_FLAG: 'true'
        - pipe: docker://rudijs/aws-cloudfront-create-invalidation:1.0.2
          variables:
             AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
             AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
             DISTRIBUTION_ID: $DISTRIBUTION_ID
pipelines:
  branches:
   staging :
      - step:
          deployment: staging
          <<: *deploy
